### ISSUE TITLE
ZOINK

### ISSUE THREAD

**Issue by MonsBaan** [Inushin/Inushin#1]
Hippity Hoppity your code is now my property C:

**Comment by Inushin** [comment]
![68747470733a2f2f692e6962622e636f2f797337475359632f49636f6e6f2d50696e6775696e6f2e706e67](https://user-images.githubusercontent.com/57062736/141106581-dc559dce-4a7c-4574-bad4-dcc9bc3fa784.png)

**Comment by Inushin** [comment]
![68747470733a2f2f692e6962622e636f2f797337475359632f49636f6e6f2d50696e6775696e6f2e706e67](https://user-images.githubusercontent.com/57062736/141106661-73fe088a-12ee-4b4b-98b4-03d5926460bf.png)
